### ISSUE TITLE
Always fail to spawn the island world type in server.

### ISSUE THREAD

**Issue by Greygreygod** [FoundSpore/IslandWorldType#3]
I follow the step to deal with the "server.properties" file.But always fail to spawn the islands.It always spawn the default world  type in server.
But it's successful in client.
[latest.log](https://github.com/FoundSpore/IslandWorldType/files/4279270/latest.log)

**Comment by FoundSpore** [comment]
Please send over your .properties file and version

**Comment by Greygreygod** [comment]
[server.properties.zip](https://github.com/FoundSpore/IslandWorldType/files/4279516/server.properties.zip)
I have to make it in the zip that i can upload it.
Version are the "1.15.2",and forge version are 31.1.17

**Comment by FoundSpore** [comment]
1. It worked fine with me. Make sure you're on the latest version of of this mod. It worked perfectly fine when I put into my own test server
 2. Please join the discord(on curse page) so I can assist you further and much faster
